-- Part 3: stage, file format and raw tables, then the first load.
USE ROLE LOADER;
USE WAREHOUSE LOADING_WH;
USE SCHEMA RAW.TPCH;

-- 1. How to read the files
CREATE FILE FORMAT IF NOT EXISTS CSV_GZ
  TYPE = CSV
  COMPRESSION = GZIP
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('')
  EMPTY_FIELD_AS_NULL = TRUE;

-- 2. Where the files land (an internal stage; an S3/ADLS/GCS external stage works the same)
CREATE STAGE IF NOT EXISTS LANDING
  FILE_FORMAT = CSV_GZ
  COMMENT = 'Files waiting to be loaded into RAW.TPCH';

-- 3. Small reference tables: copy straight from the sample data
CREATE OR REPLACE TABLE CUSTOMER AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;
CREATE OR REPLACE TABLE NATION   AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;
CREATE OR REPLACE TABLE REGION   AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION;
CREATE OR REPLACE TABLE PART     AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART;
CREATE OR REPLACE TABLE SUPPLIER AS SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER;

-- 4. Fact tables: same columns as the source plus two audit columns
CREATE TABLE IF NOT EXISTS ORDERS AS
  SELECT *, CURRENT_TIMESTAMP()::TIMESTAMP_LTZ AS _LOADED_AT, ''::VARCHAR AS _SOURCE_FILE
  FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS WHERE FALSE;

CREATE TABLE IF NOT EXISTS LINEITEM AS
  SELECT *, CURRENT_TIMESTAMP()::TIMESTAMP_LTZ AS _LOADED_AT, ''::VARCHAR AS _SOURCE_FILE
  FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM WHERE FALSE;

-- 5. Play the source system: drop history up to June 1998 into the stage as gzip CSV files
COPY INTO @LANDING/orders/batch_1998_06/
  FROM (SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS WHERE O_ORDERDATE < '1998-07-01')
  HEADER = TRUE;

COPY INTO @LANDING/lineitem/batch_1998_06/
  FROM (SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM
        WHERE L_ORDERKEY IN (SELECT O_ORDERKEY FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS
                             WHERE O_ORDERDATE < '1998-07-01'))
  HEADER = TRUE;

LIST @LANDING;

-- 6. Peek at staged files before loading them
SELECT $1 AS orderkey, $2 AS custkey, $5 AS orderdate, METADATA$FILENAME
FROM @LANDING/orders/ (FILE_FORMAT => 'CSV_GZ')
LIMIT 5;

-- 7. Load: run airflow/dags/sql/load_raw_orders.sql (the same statements Airflow runs daily)

-- 8. Check what happened, file by file
SELECT FILE_NAME, STATUS, ROW_COUNT, ROW_PARSED, FIRST_ERROR_MESSAGE, LAST_LOAD_TIME
FROM TABLE(INFORMATION_SCHEMA.COPY_HISTORY(
       TABLE_NAME => 'RAW.TPCH.ORDERS',
       START_TIME => DATEADD(HOUR, -24, CURRENT_TIMESTAMP())));
