-- Part 7: simulate tomorrow's delivery (orders from July 1998 onwards).
USE ROLE LOADER;
USE WAREHOUSE LOADING_WH;
USE SCHEMA RAW.TPCH;

COPY INTO @LANDING/orders/batch_1998_08/
  FROM (SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS WHERE O_ORDERDATE >= '1998-07-01')
  HEADER = TRUE;

COPY INTO @LANDING/lineitem/batch_1998_08/
  FROM (SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM
        WHERE L_ORDERKEY IN (SELECT O_ORDERKEY FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS
                             WHERE O_ORDERDATE >= '1998-07-01'))
  HEADER = TRUE;

-- a customer changes segment: picked up by the snapshot in part 7
UPDATE CUSTOMER SET C_MKTSEGMENT = 'AUTOMOBILE' WHERE C_CUSTKEY = 1;
